BG_COLOR = '#404040'
HISTORICAL_DATA_BASE = 'historical_data'
TICKERS = ['GRASIM', 'NTPC', 'ADANIPORTS', 'JSWSTEEL', 'TITAN', 'COALINDIA', 'KOTAKBANK', 'HINDALCO',
           'POWERGRID', 'SHREECEM', 'DIVISLAB', 'LT', 'TECHM', 'SBILIFE', 'M&M', 'TATASTEEL',
           'TATAMOTORS', 'APOLLOHOSP', 'HEROMOTOCO', 'SBIN', 'SUNPHARMA', 'ULTRACEMCO', 'WIPRO',
           'INFY', 'BAJAJFINSV', 'BAJFINANCE', 'AXISBANK', 'ONGC', 'ITC', 'HCLTECH', 'TCS', 'BRITANNIA',
           'HDFCBANK', 'BPCL', 'ICICIBANK', 'HINDUNILVR', 'NESTLEIND', 'TATACONSUM', 'MARUTI', 'CIPLA',
           'BAJAJ-AUTO', 'UPL', 'DRREDDY', 'RELIANCE', 'HDFCLIFE', 'HDFC', 'ASIANPAINT', 'BHARTIARTL',
           'INDUSINDBK', 'EICHERMOT']
USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0'
YAHOO_MAIN_DOMAIN = 'query1.finance.yahoo.com/v7/finance/download'
YAHOO_FINANCE_URL = 'https://{}/{}'
